### PR TITLE
feat: working Agoric initiator

### PR DESCRIPTION
**Pull request by michaelfig**
Now working end-to-end with https://github.com/smartcontractkit/external-adapters-js/pull/114 and https://github.com/Agoric/dapp-oracle

### CODE REVIEW

**Comment by RodrigoAD** [comment]
Hi @michaelfig, thanks for the good work. If you could add the necessary tests it would be ready

**Comment by michaelfig** [comment]
> Hi @michaelfig, thanks for the good work. If you could add the necessary tests it would be ready

R4R!

**Comment by michaelfig** [comment]
@RodrigoAD this is ready to go, IMO.

Do note that the Required "imports" check seems to be misconfigured.  Instead, it should be "golang/static / Imports".  Could you please change this setting in the Github configuration for this repository?

**Comment by michaelfig** [comment]
@RodrigoAD @rigario this is ready for review, PTAL.

**Comment by RodrigoAD** [comment]
Overall looks good, just this final detail. We've recently added prometheus metrics exporting, if you include it as well. You can follow this: https://github.com/smartcontractkit/external-initiator/blob/c2e16a091d87e91a2b78df2f5d8b65814a959d12/blockchain/bsn-irita.go#L141

**Comment by michaelfig** [comment]
> We've recently added prometheus metrics exporting, if you could include it as well.

Done!  R4R as soon as the tests pass.

**Review by RodrigoAD — APPROVED** [review]
Thanks @michaelfig !

**Pull request merged**
