### PR TITLE
External Initiator for Klaytn

### PR DESCRIPTION
**Pull request by aalu1418**
Original PR submitted by Klatyn team https://github.com/smartcontractkit/external-initiator/pull/92

This branch addresses the requested changes from that PR.

### CODE REVIEW

**Comment by ebarakos** [comment]
Since this will need to be changed according to the new RunLog refactoring, doesn't it make sense to do the refactoring directly in this PR and merge against `feature/fluxmonitor` @aalu1418 ?

**Comment by aalu1418** [comment]
@ebarakos That's a good point! I was thinking it would be good just to get it merged, in case someone wants to use it right now. And then we add it to our list of blockchains that need additional refactoring?

**Review by ebarakos — APPROVED** [review]
LGTM, adheres to other implementations. It would be good if we could have some testing against the actual chain before merging.

**Comment by aalu1418** [comment]
Successfully triggered with proper parameters passed!

**Pull request merged**
